--Criando tabelas

CREATE TABLE CH_BAIRRO (
    ID               NUMBER NOT NULL,
    DESCRICAO        VARCHAR2(50),
    DESCRICAO_RUA    VARCHAR2(50),
    NUMERO           NUMBER(7),
    CEP              NUMBER(8),
    ID_CIDADE        NUMBER,
    CIDADE_CIDADE_ID NUMBER NOT NULL,
    ENDERECO_ID      NUMBER NOT NULL
);

CREATE UNIQUE INDEX CH_BAIRRO_IDX ON
    CH_BAIRRO (
        ENDERECO_ID
    ASC );

ALTER TABLE CH_BAIRRO ADD CONSTRAINT CH_BAIRRO_PK PRIMARY KEY ( ID );

CREATE TABLE CH_CIDADE (
    ID        NUMBER,
    DESCRICAO VARCHAR2(50),
    ID_ESTADO NUMBER,
    ESTADO_ID NUMBER NOT NULL,
    CIDADE_ID NUMBER NOT NULL
);

ALTER TABLE CH_CIDADE ADD CONSTRAINT CH_CIDADE_PK PRIMARY KEY ( CIDADE_ID );

CREATE TABLE CH_CLINICA (
    ID                  NUMBER,
    DESCRICAO           VARCHAR2(200),
    CNPJ                NUMBER(14),
    EMAIL_REPRESENTANTE VARCHAR2(100),
    ID_BAIRRO           NUMBER,
    CLINICA_ID          NUMBER NOT NULL
);

ALTER TABLE CH_CLINICA ADD CONSTRAINT CH_CLINICA_PK PRIMARY KEY ( CLINICA_ID );

CREATE TABLE CH_CONSULTA (
    ID         NUMBER,
    DATA       DATE,
    HORARIO    DATE,
    DESCRICAO  VARCHAR2(100),
    ID_CLIENTE NUMBER,
    ID_DOUTOR  NUMBER,
    USUARIO_ID NUMBER NOT NULL,
    DOUTOR_ID  NUMBER NOT NULL
);

CREATE TABLE CH_CONVENIO (
    ID            NUMBER,
    NOME_CONVENIO VARCHAR2(100),
    DESCRICAO     VARCHAR2(100),
    PRECO         NUMBER(7),
    CONVENIO_ID   NUMBER NOT NULL
);

ALTER TABLE CH_CONVENIO ADD CONSTRAINT CH_CONVENIO_PK PRIMARY KEY ( CONVENIO_ID );

CREATE TABLE CH_DOUTOR (
    ID                 NUMBER NOT NULL,
    NOME               VARCHAR2(50),
    CPF                NUMBER(11),
    EMAIL              VARCHAR2(100),
    NASCIMENTO         DATE,
    TELEFONE           NUMBER(16),
    ID_CLINICA         NUMBER,
    CLINICA_CLINICA_ID NUMBER NOT NULL
);

ALTER TABLE CH_DOUTOR ADD CONSTRAINT CH_DOUTOR_PK PRIMARY KEY ( ID );

CREATE TABLE CH_ENDERECO (
    ID        NUMBER NOT NULL,
    ID_PAIS   NUMBER,
    ID_ESTADO NUMBER,
    ID_CIDADE NUMBER,
    ID_BAIRRO NUMBER
);

ALTER TABLE CH_ENDERECO ADD CONSTRAINT CH_ENDERECO_PK PRIMARY KEY ( ID );

CREATE TABLE CH_ESTADO (
    ID        NUMBER NOT NULL,
    DESCRICAO VARCHAR2(50),
    ID_PAIS   NUMBER,
    PAIS_ID   NUMBER NOT NULL
);

ALTER TABLE CH_ESTADO ADD CONSTRAINT CH_ESTADO_PK PRIMARY KEY ( ID );

CREATE TABLE CH_PAIS (
    ID        NUMBER NOT NULL,
    DESCRICAO VARCHAR2(50)
);

ALTER TABLE CH_PAIS ADD CONSTRAINT CH_PAIS_PK PRIMARY KEY ( ID );

CREATE TABLE CH_USUARIO (
    ID                   NUMBER NOT NULL,
    NOME                 VARCHAR2(50),
    CPF                  NUMBER(11),
    EMAIL                VARCHAR2(100),
    NASCIMENTO           DATE,
    TELEFONE             NUMBER(16),
    ID_BAIRRO            NUMBER,
    ID_CONVENIO          NUMBER,
    CONVENIO_CONVENIO_ID NUMBER NOT NULL,
    ENDERECO_ID          NUMBER NOT NULL
);

ALTER TABLE CH_USUARIO ADD CONSTRAINT CH_USUARIO_PK PRIMARY KEY ( ID );

ALTER TABLE CH_BAIRRO
    ADD CONSTRAINT CH_BAIRRO_CIDADE_FK FOREIGN KEY ( CIDADE_CIDADE_ID )
        REFERENCES CH_CIDADE ( CIDADE_ID );

ALTER TABLE CH_BAIRRO
    ADD CONSTRAINT CH_BAIRRO_ENDERECO_FK FOREIGN KEY ( ENDERECO_ID )
        REFERENCES CH_ENDERECO ( ID );

ALTER TABLE CH_CIDADE
    ADD CONSTRAINT CH_CIDADE_ESTADO_FK FOREIGN KEY ( ESTADO_ID )
        REFERENCES CH_ESTADO ( ID );

ALTER TABLE CH_CONSULTA
    ADD CONSTRAINT CH_CONSULTA_DOUTOR_FK FOREIGN KEY ( DOUTOR_ID )
        REFERENCES CH_DOUTOR ( ID );

ALTER TABLE CH_CONSULTA
    ADD CONSTRAINT CH_CONSULTA_USUARIO_FK FOREIGN KEY ( USUARIO_ID )
        REFERENCES CH_USUARIO ( ID );

ALTER TABLE CH_DOUTOR
    ADD CONSTRAINT CH_DOUTOR_CLINICA_FK FOREIGN KEY ( CLINICA_CLINICA_ID )
        REFERENCES CH_CLINICA ( CLINICA_ID );

ALTER TABLE CH_ESTADO
    ADD CONSTRAINT CH_ESTADO_PAIS_FK FOREIGN KEY ( PAIS_ID )
        REFERENCES CH_PAIS ( ID );

ALTER TABLE CH_USUARIO
    ADD CONSTRAINT CH_USUARIO_CONVENIO_FK FOREIGN KEY ( CONVENIO_CONVENIO_ID )
        REFERENCES CH_CONVENIO ( CONVENIO_ID );

ALTER TABLE CH_USUARIO
    ADD CONSTRAINT CH_USUARIO_ENDERECO_FK FOREIGN KEY ( ENDERECO_ID )
        REFERENCES CH_ENDERECO ( ID );

CREATE SEQUENCE CH_CIDADE_CIDADE_ID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER CH_CIDADE_CIDADE_ID_TRG BEFORE
    INSERT ON CH_CIDADE
    FOR EACH ROW
    WHEN ( NEW.CIDADE_ID IS NULL )
BEGIN
    :NEW.CIDADE_ID := CH_CIDADE_CIDADE_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE CH_CLINICA_CLINICA_ID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER CH_CLINICA_CLINICA_ID_TRG BEFORE
    INSERT ON CH_CLINICA
    FOR EACH ROW
    WHEN ( NEW.CLINICA_ID IS NULL )
BEGIN
    :NEW.CLINICA_ID := CH_CLINICA_CLINICA_ID_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE CH_CONVENIO_CONVENIO_ID_SEQ START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER CH_CONVENIO_CONVENIO_ID_TRG BEFORE
    INSERT ON CH_CONVENIO
    FOR EACH ROW
    WHEN ( NEW.CONVENIO_ID IS NULL )
BEGIN
    :NEW.CONVENIO_ID := CH_CONVENIO_CONVENIO_ID_SEQ.NEXTVAL;
END;
/