-- Criar sequências primeiro
CREATE SEQUENCE CH_CIDADE_CIDADE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_CLINICA_CLINICA_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_PLANO_PLANO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_SERVICOS_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_SERVICOS_PLANO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_PLANO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_BAIRRO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_ENDERECO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_CLINICA_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_CLINICA_DOUTORES_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_DOUTOR_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_USUARIO_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_CARTEIRINHA_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE CH_CONSULTA_ID_SEQ START WITH 1 NOCACHE ORDER;


CREATE TABLE CH_ENDERECO (
    ID        NUMBER PRIMARY KEY NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO NUMBER NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    PAIS VARCHAR(20) NOT NULL
);

CREATE TABLE CH_CLINICA (
    ID NUMBER PRIMARY KEY NOT NULL,
    DESCRICAO           VARCHAR2(200),
    CNPJ                NUMBER(14),
    EMAIL_REPRESENTANTE VARCHAR2(100),
    ID_ENDERECO           NUMBER,
    CONSTRAINT CH_CLINICA_BAIRRO_FK FOREIGN KEY (ID_ENDERECO) REFERENCES CH_ENDERECO(ID)
);

CREATE TABLE CH_DOUTOR (
    ID                 NUMBER PRIMARY KEY NOT NULL,
    NOME               VARCHAR2(50),
    CPF                NUMBER(11),
    EMAIL              VARCHAR2(100),
    NASCIMENTO         DATE,
    TELEFONE           NUMBER(16),
    CLINICA_ID NUMBER NOT NULL,
    CONSTRAINT CH_DOUTOR_CLINICA_FK FOREIGN KEY (CLINICA_ID) REFERENCES CH_CLINICA(ID)
);

CREATE TABLE CH_CLINICA_DOUTORES(
    ID NUMBER PRIMARY KEY NOT NULL,
    CLINICA_ID NUMBER,
    DOUTOR_ID NUMBER,
    CONSTRAINT CH_CLINICA_FK FOREIGN KEY (CLINICA_ID) REFERENCES CH_CLINICA(ID),
    CONSTRAINT CH_DOUTOR_FK FOREIGN KEY (DOUTOR_ID) REFERENCES CH_DOUTOR(ID)
);

CREATE TABLE CH_SERVICOS
(
    ID NUMBER PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(30)
)

CREATE TABLE CH_PLANO
(
    ID NUMBER PRIMARY KEY NOT NULL,
    NOME VARCHAR(30),
    PRECO NUMBER(10,2)
)

CREATE TABLE CH_SERVICOS_PLANO
(
    ID NUMBER PRIMARY KEY NOT NULL,
    SERVICOS_ID NUMBER,
    PLANO_ID NUMBER,
    CONSTRAINT FK_SERVICOS FOREIGN KEY (SERVICOS_ID) REFERENCES CH_SERVICOS(ID),
    CONSTRAINT FK_PLANO FOREIGN KEY (PLANO_ID) REFERENCES CH_PLANO(ID)
);

CREATE TABLE CH_USUARIO (
    ID                   NUMBER PRIMARY KEY NOT NULL,
    NOME                 VARCHAR2(50),
    CPF                  NUMBER(11),
    EMAIL                VARCHAR2(100),
    NASCIMENTO           DATE,
    TELEFONE             NUMBER(16),
    ENDERECO_ID          NUMBER NOT NULL,
    CONSTRAINT CH_USUARIO_ENDERECO_FK FOREIGN KEY (ENDERECO_ID) REFERENCES CH_ENDERECO(ID)
);

CREATE TABLE CH_CARTEIRINHA(
    ID NUMBER PRIMARY KEY NOT NULL,
    NUMERO VARCHAR2(10),
    EMISSAO DATE,
    VALIDADE DATE,
    USUARIO_ID NUMBER NOT NULL,
    PLANO_ID NUMBER NOT NULL,
    CONSTRAINT CH_DONO_CARTEIRINHA_FK FOREIGN KEY (ID) REFERENCES CH_USUARIO(ID),
    CONSTRAINT CH_TIPO_CONVENIO_FK FOREIGN KEY (ID) REFERENCES CH_PLANO(ID)
);

CREATE TABLE CH_CONSULTA (
    ID         NUMBER PRIMARY KEY NOT NULL,
    DATA       DATE,
    OBSERVACOES  VARCHAR2(500),
    CLINICA_ID NUMBER,
    DOUTOR_ID  NUMBER NOT NULL,
    USUARIO_ID NUMBER NOT NULL,
    SERVICOS_ID NUMBER NOT NULL,
    CONSTRAINT CH_CONSULTA_CLINICA_FK FOREIGN KEY (CLINICA_ID) REFERENCES CH_CLINICA(ID),
    CONSTRAINT CH_CONSULTA_DOUTOR_FK FOREIGN KEY (DOUTOR_ID) REFERENCES CH_DOUTOR(ID),
    CONSTRAINT CH_CONSULTA_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES CH_USUARIO(ID),
    CONSTRAINT CH_CONSULTA_SERVICOS_FK FOREIGN KEY (SERVICOS_ID) REFERENCES CH_SERVICOS(ID)
);

select * from CH_USUARIO